# Generated by Django 5.0.7 on 2024-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
