# Generated by Django 5.0.7 on 2024-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_remove_dish_ingredients_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='kitchen.ingredient'),
        ),
    ]
