# Generated by Django 5.0.7 on 2024-09-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_dish_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('name',), 'verbose_name_plural': 'dishes'},
        ),
    ]
